Repository C23-GT01/backend-api, pull requests merged in 2023-11, with the labels that each got.

#6 Modularization
  .eslintrc.json
  package-lock.json
  package.json
  src/handler.js
  src/products.js
  src/routes.js
  src/server.js
Labels: documentation, Asignment

#11 Api plugin services
  package-lock.json
  package.json
  src/api/products/handler.js
  src/api/products/index.js
  src/api/products/routes.js
  src/api/umkm/handler.js
  src/api/umkm/index.js
  src/api/umkm/routes.js
  src/exceptions/ClientError.js
  src/exceptions/InvariantError.js
  src/handler.js
  src/products.js
  src/routes.js
  src/server.js
  src/services/inMemory/ProductsService.js
  src/services/inMemory/UmkmService.js
  src/services/inMemory/a.json
  src/services/postgres/ProductsService.js
  src/services/postgres/UmkmService.js
Labels: Asignment

#12 impllement data validation
  package-lock.json
  package.json
  src/api/products/handler.js
  src/api/products/index.js
  src/api/umkm/handler.js
  src/exceptions/NotFoundError.js
  src/server.js
  src/services/inMemory/ProductsService.js
  src/services/inMemory/UmkmService.js
  src/services/inMemory/a.json
  src/validator/products/index.js
  src/validator/products/schema.js
  src/validator/umkm/index.js
  src/validator/umkm/schema.js
Labels: Asignment

#13 connect to database
  .gitignore
  migrations/1700134692676_create-table-products.js
  migrations/1700146434773_create-table-umkm.js
  package-lock.json
  package.json
  src/api/products/handler.js
  src/api/umkm/handler.js
  src/api/umkm/routes.js
  src/server.js
  src/services/postgres/ProductsService.js
  src/services/postgres/UmkmService.js
  src/utils/index.js
Labels: Asignment

#14 Development
  .eslintrc.json
  .gitignore
  migrations/1700134692676_create-table-products.js
  migrations/1700146434773_create-table-umkm.js
  package-lock.json
  package.json
  src/api/products/handler.js
  src/api/products/index.js
  src/api/products/routes.js
  src/api/umkm/handler.js
  src/api/umkm/index.js
  src/api/umkm/routes.js
  src/exceptions/ClientError.js
  src/exceptions/InvariantError.js
  src/exceptions/NotFoundError.js
  src/server.js
  src/services/inMemory/ProductsService.js
  src/services/inMemory/UmkmService.js
  src/services/postgres/ProductsService.js
  src/services/postgres/UmkmService.js
  src/utils/index.js
  src/validator/products/index.js
  src/validator/products/schema.js
  src/validator/umkm/index.js
  src/validator/umkm/schema.js
Labels: documentation, checkpoint, Asignment

#15 Upload image plugin
  .gitignore
  package-lock.json
  package.json
  src/api/uploads/handler.js
  src/api/uploads/index.js
  src/api/uploads/routes.js
  src/server.js
  src/services/storage/StorageService.js
  src/validator/uploads/index.js
  src/validator/uploads/schema.js
Labels: Asignment

#16 Authentication and authorization
  migrations/1700134692676_create-table-products.js
  migrations/1700146434773_create-table-umkm.js
  migrations/1700212790710_create-table-users.js
  migrations/1700215030481_create-table-authentications.js
  package-lock.json
  package.json
  src/api/authentications/handler.js
  src/api/authentications/index.js
  src/api/authentications/routes.js
  src/api/products/handler.js
  src/api/products/routes.js
  src/api/umkm/handler.js
  src/api/umkm/routes.js
  src/api/uploads/routes.js
  src/api/users/handler.js
  src/api/users/index.js
  src/api/users/routes.js
  src/exceptions/AuthenticationError.js
  src/exceptions/AuthorizationError.js
  src/server.js
  src/services/postgres/AuthenticationsService.js
  src/services/postgres/ProductsService.js
  src/services/postgres/UmkmService.js
  src/services/postgres/UsersService.js
  src/tokenize/TokenManager.js
  src/utils/index.js
  src/validator/authentications/index.js
  src/validator/authentications/schema.js
  src/validator/products/schema.js
  src/validator/users/index.js
  src/validator/users/schema.js
Labels: Asignment

#17 Testing and fixing
  src/api/products/handler.js
  src/api/products/routes.js
  src/api/umkm/handler.js
  src/api/uploads/handler.js
  src/api/users/handler.js
  src/services/postgres/ProductsService.js
  src/utils/index.js
Labels: bug, testing, fix
